// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.OneNote")]
[assembly: AssemblyProductAttribute("Plainion.OneNote")]
[assembly: AssemblyDescriptionAttribute("Plainion.OneNote")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2018")]
[assembly: AssemblyVersionAttribute("1.2")]
[assembly: AssemblyFileVersionAttribute("1.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.OneNote";
        internal const System.String AssemblyProduct = "Plainion.OneNote";
        internal const System.String AssemblyDescription = "Plainion.OneNote";
        internal const System.String AssemblyCopyright = "Copyright @ 2018";
        internal const System.String AssemblyVersion = "1.2";
        internal const System.String AssemblyFileVersion = "1.2";
    }
}
