// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Plainion.OneNote")]
[assembly: AssemblyProduct("Plainion.OneNote")]
[assembly: AssemblyDescription("Plainion.OneNote")]
[assembly: AssemblyCopyright("Copyright @ 2019")]
[assembly: AssemblyVersion("1.7")]
[assembly: AssemblyFileVersion("1.7")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.OneNote";
        internal const System.String AssemblyProduct = "Plainion.OneNote";
        internal const System.String AssemblyDescription = "Plainion.OneNote";
        internal const System.String AssemblyCopyright = "Copyright @ 2019";
        internal const System.String AssemblyVersion = "1.7";
        internal const System.String AssemblyFileVersion = "1.7";
    }
}
